CREATE TABLE IF NOT EXISTS demox_website_envs (
  website_id VARCHAR(128) NOT NULL,
  env_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (website_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
