import React from "react";
import { Check, ServerOff } from "lucide-react";
import { useLanguage } from "@/hooks/use-language";
import { GeoArticle, GeoSectionHeading } from "@/components/GeoArticle";

const PAGE_URL = "https://www.demox.site/when-to-use-demox";
const PUBLISHED_AT = "2026-09-14";
const UPDATED_AT = "2026-09-14";

const copy = {
  zh: {
    eyebrow: "适用场景",
    title: "什么时候该用 Demox，什么时候不该用？",
    answer:
      "Demox 适合两类产物。一类是静态网站：单个 HTML、根目录含 index.html 的 dist、build 或 ZIP，以及 PDF、Markdown、TXT、DOCX。上传后得到带 HTTPS 和 CDN 的公开链接，入口是网页控制台、CLI、MCP 或 API。另一类是 Node 接口：把后端改成 handler(request, env)，用 demox functions push 挂到同一站点，页面里 fetch('/api/标识') 会转到对应函数。环境变量按函数设置；首次上传创建 v1，production 和 develop 都指向 v1，之后再推送不会自动改别名。Python、PHP、Java 运行时尚未提供。Express listen 不能原样上传。需要直连私密数据库、常驻进程或没有静态导出的服务端渲染，仍需独立后端或先改造。Demox 不声称替代完整 CI/CD 平台。",
    published: "发布于 2026-09-14",
    updated: "更新于 2026-09-14",
    author: "Demox 团队",
    primaryCta: "上传并发布",
    secondaryCta: "查看文档",
    tableEyebrow: "对照表",
    tableTitle: "按你手里的产物判断",
    headers: ["你手里有什么", "适合 Demox？", "怎么发"],
    rows: [
      ["AI 生成的单个 HTML", "适合", "网页上传，或 demox deploy 该文件"],
      ["React / Vue / Vite 的 dist 或 build", "适合", "demox deploy ./dist，入口必须是根目录 index.html"],
      ["PDF、Markdown、TXT、DOCX", "适合", "网页上传或 demox deploy 该文件"],
      ["已导出 handler(request, env) 的 Node 接口", "适合", "demox functions push，再 demox env set"],
      ["仍在 app.listen 的 Express 服务", "不适合直接上传", "先改成 handler，不要让进程监听端口"],
      ["Python、PHP 或 Java 服务", "目前不适合", "继续使用独立后端"],
      ["必须直连私密数据库、写本地磁盘或常驻进程", "默认不适合", "密钥可走函数 env，但运行时限制仍在"],
      ["没有静态导出的服务端渲染应用", "不适合", "先产出静态目录，或换能跑该运行时的平台"],
    ],
    fitEyebrow: "边界",
    fitTitle: "可以直接发，和需要换路的情况",
    goodTitle: "可以直接发",
    goodItems: [
      "前端 Demo、交互原型、客户评审页和活动页",
      "AI 助手生成的 HTML 单页",
      "已经构建完成的静态站点",
      "需要和页面一起发布的 Node handler",
    ],
    badTitle: "需要先改造或换平台",
    badItems: [
      "Python、PHP、Java 或其他非 Node 运行时",
      "Express listen、WebSocket 常驻连接、定时守护进程",
      "没有静态导出结果的 SSR 应用",
      "把 Demox 当成 Vercel 或 Netlify 的完整替代",
    ],
    caseEyebrow: "第一方证据",
    caseTitle: "Demox 自己也是这样发布的",
    caseBody:
      "主站 https://www.demox.site 是平台上的一个普通站点。页面用 demox deploy 发布静态构建产物；鉴权、站点、MCP 和证书续期等业务后端用 demox functions push 挂在同一站点上。函数环境变量按函数设置，别名 production 和 develop 需要显式指向版本。这不是虚构案例，而是当前仓库 AGENTS.md 记录的发布方式。可计量的访问量、客户数或可用性数字不在本页声称范围内。",
    caseCta: "阅读自托管说明",
    closeTitle: "不确定能不能发？先对表，再上传。",
    closeBody: "静态产物走 demox deploy。Node 接口先改 handler，再 functions push。",
  },
  en: {
    eyebrow: "When to use",
    title: "When is Demox a fit, and when is it not?",
    answer:
      "Demox fits two kinds of output. Static sites: a single HTML file, a dist, build, or ZIP with index.html at the root, and PDF, Markdown, TXT, or DOCX. Upload them to get a public HTTPS link on CDN through the web console, CLI, MCP, or API. Node APIs: export handler(request, env), then demox functions push onto the same site. The page calls fetch('/api/{slug}'). Env is per function. The first upload creates v1 and points production and develop at v1; later uploads do not move aliases. Python, PHP, and Java runtimes are not available. Express listen cannot be uploaded as-is. Apps that need a private database connection, a long-lived process, or server rendering without a static export still need a separate backend or a rewrite. Demox does not claim to replace a full CI/CD platform.",
    published: "Published Sep 14, 2026",
    updated: "Updated Sep 14, 2026",
    author: "Demox team",
    primaryCta: "Upload now",
    secondaryCta: "Read the docs",
    tableEyebrow: "Comparison",
    tableTitle: "Match Demox to what you already have",
    headers: ["What you have", "Fit?", "How to publish"],
    rows: [
      ["One AI-generated HTML file", "Yes", "Web upload or demox deploy that file"],
      ["React / Vue / Vite dist or build", "Yes", "demox deploy ./dist with index.html at the root"],
      ["PDF, Markdown, TXT, or DOCX", "Yes", "Web upload or demox deploy the file"],
      ["A Node handler(request, env)", "Yes", "demox functions push, then demox env set"],
      ["Express with app.listen", "Not as-is", "Rewrite as a handler; do not listen on a port"],
      ["Python, PHP, or Java services", "Not yet", "Keep a separate backend"],
      ["Private database, local disk, or a daemon", "Usually no", "Secrets can use function env; runtime limits remain"],
      ["SSR without a static export", "No", "Export static files first, or use a platform that runs that runtime"],
    ],
    fitEyebrow: "Boundaries",
    fitTitle: "What can ship now, and what cannot",
    goodTitle: "Ready to publish",
    goodItems: [
      "Frontend demos, prototypes, review pages, and campaign pages",
      "Single HTML files generated by an AI assistant",
      "Already-built static sites",
      "Node handlers that should ship with the same site",
    ],
    badTitle: "Needs a rewrite or another platform",
    badItems: [
      "Python, PHP, Java, or any non-Node runtime",
      "Express listen, long-lived WebSockets, or daemon processes",
      "Server-rendered apps without a static export",
      "Treating Demox as a full Vercel or Netlify replacement",
    ],
    caseEyebrow: "First-party evidence",
    caseTitle: "Demox publishes itself this way",
    caseBody:
      "The main site at https://www.demox.site is an ordinary site on the platform. Pages ship with demox deploy. Auth, website, MCP, and certificate-renewal backends ship with demox functions push on the same site. Function env is per function. The production and develop aliases must be pointed at a version explicitly. This is the release path recorded in the repository AGENTS.md, not a hypothetical. This page does not claim traffic, customer, or uptime numbers.",
    caseCta: "Read the self-hosting note",
    closeTitle: "Unsure? Check the table, then upload.",
    closeBody: "Static output uses demox deploy. Node APIs become handlers, then functions push.",
  },
} as const;

export const WhenToUseDemox: React.FC = () => {
  const { language } = useLanguage();
  const t = copy[language === "en" ? "en" : "zh"];

  return (
    <GeoArticle
      url={PAGE_URL}
      published={PUBLISHED_AT}
      updated={UPDATED_AT}
      language={language === "en" ? "en" : "zh"}
      eyebrow={t.eyebrow}
      title={t.title}
      answer={t.answer}
      author={t.author}
      publishedLabel={t.published}
      updatedLabel={t.updated}
      ctas={[
        { href: "/console/projects", label: t.primaryCta, primary: true },
        { href: "/doc", label: t.secondaryCta },
      ]}
    >
      <section className="mx-auto max-w-5xl py-14 md:py-20" aria-labelledby="fit-table">
        <GeoSectionHeading eyebrow={t.tableEyebrow} title={t.tableTitle} id="fit-table" />
        <div className="mt-8 overflow-x-auto rounded-2xl border border-[var(--stitch-line)]">
          <table className="min-w-[36rem] w-full text-left text-sm">
            <thead className="bg-[var(--stitch-blue-soft)] font-bold">
              <tr>
                {t.headers.map((header) => (
                  <th key={header} className="px-4 py-3 md:px-5">
                    {header}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--stitch-line)]">
              {t.rows.map((row) => (
                <tr key={row[0]}>
                  {row.map((cell) => (
                    <td key={cell} className="px-4 py-3 align-top leading-6 text-[var(--stitch-muted)] md:px-5">
                      {cell}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mx-auto max-w-5xl pb-14 md:pb-20" aria-labelledby="fit-lists">
        <GeoSectionHeading eyebrow={t.fitEyebrow} title={t.fitTitle} id="fit-lists" />
        <div className="mt-10 grid gap-4 md:grid-cols-2">
          <FitCard icon={Check} title={t.goodTitle} items={t.goodItems} />
          <FitCard icon={ServerOff} title={t.badTitle} items={t.badItems} muted />
        </div>
      </section>

      <section className="mx-auto max-w-5xl rounded-2xl border border-[var(--stitch-line)] bg-[var(--stitch-surface)] p-7 md:p-10" aria-labelledby="self-host">
        <p className="font-mono text-xs uppercase tracking-[0.2em] text-[var(--stitch-muted)]">{t.caseEyebrow}</p>
        <h2 id="self-host" className="mt-3 text-2xl font-black tracking-tight md:text-3xl">
          {t.caseTitle}
        </h2>
        <p className="mt-5 max-w-3xl leading-8 text-[var(--stitch-muted)]">{t.caseBody}</p>
        <a href="/how-demox-hosts-itself" className="mt-6 inline-flex text-sm font-bold">
          {t.caseCta}
        </a>
      </section>

      <section className="mx-auto mt-14 max-w-5xl overflow-hidden rounded-3xl bg-[var(--stitch-ink)] px-7 py-12 text-[var(--stitch-surface)] md:mt-20 md:px-12 md:py-16">
        <h2 className="max-w-3xl text-3xl font-black leading-tight tracking-[-0.035em] md:text-5xl">{t.closeTitle}</h2>
        <p className="mt-5 max-w-2xl leading-7 opacity-70">{t.closeBody}</p>
      </section>
    </GeoArticle>
  );
};

function FitCard({
  icon: Icon,
  title,
  items,
  muted = false,
}: {
  icon: React.ComponentType<{ size?: number }>;
  title: string;
  items: readonly string[];
  muted?: boolean;
}) {
  return (
    <section className={`rounded-2xl border border-[var(--stitch-line)] p-6 md:p-8 ${muted ? "bg-transparent" : "bg-[var(--stitch-surface)]"}`}>
      <div className="flex items-center gap-3">
        <span className="rounded-lg bg-[var(--stitch-blue-soft)] p-2">
          <Icon size={19} />
        </span>
        <h3 className="text-xl font-bold">{title}</h3>
      </div>
      <ul className="mt-6 space-y-4">
        {items.map((item) => (
          <li key={item} className="flex gap-3 text-sm leading-6 text-[var(--stitch-muted)]">
            <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--stitch-ink)]" />
            {item}
          </li>
        ))}
      </ul>
    </section>
  );
}

export default WhenToUseDemox;
